export default [
  {
    id: 1,
    img: 'images/objectif.jpg',
    title: ' L\'HISTOIRE DE L\'ASSOCIATION',
    presentation: [
      '« Bonjour et bienvenue !',
      'L’association Kart Club Découverte vient d’être créée pour le plus grand nombre, avec plusieurs objectifs autour de la pratique du kart : des journées découverte solidaires pour un public à budget restreint, des sorties conviviales avec les membres pratiquants, le prêt d’équipement pilotes pour apporter plus de sécurité lors des sorties (combinaisons, gants, minerves, protège-côtes, chaussures, casques).',
      'Après une longue expérience de plusieurs dizaines d’années dans le monde professionnel du kart, j’avais envie de partager cette passion d’une autre façon en créant cette association. C’est pourquoi je me suis entouré de personnes motivées pour faire vivre ces idées !',
      'Ainsi, que vous deveniez membres pratiquants, bénévoles pour soutenir les idées, ou bienfaiteurs, Kart Club Découverte aura le plaisir de vous accueillir dans ses différents projets !',
      'N’oubliez pas, le kart c’est avant tout du plaisir ; quand il n’est plus là, le talent ne suffit plus. »',
      'Régis Glaud Président KCD.',
    ],
  },
  {
    id: 2,
    img: 'images/objectifs.jpg',
    title: 'LES OBJECTIFS DE L\'ASSOCIATION',
    presentation: [
      'Kart Club Découverte (KCD) est une association « loi 1901 » qui a pour but de collecter des fonds afin de financer plusieurs projets :',
      '✅ 𝐃𝐄𝐒 𝐒𝐎𝐑𝐓𝐈𝐄𝐒 𝐃𝐄𝐂𝐎𝐔𝐕𝐄𝐑𝐓𝐄𝐒 𝐒𝐔𝐑 𝐃𝐈𝐅𝐅𝐄𝐑𝐄𝐍𝐓𝐒 𝐂𝐈𝐑𝐂𝐔𝐈𝐓𝐒 𝐏𝐎𝐔𝐑 𝐋𝐄𝐒 𝐌𝐄𝐌𝐁𝐑𝐄𝐒 𝐏𝐑𝐀𝐓𝐈𝐐𝐔𝐀𝐍𝐓𝐒 organisées tout au long de l’année. Ces journées destinées aux grands comme aux petits, aux débutants comme au initiés proposeront de pratiquer le karting sous différentes formes (type roulage location, course loisir, stage de pilotage…) avec une aide financière.',
      '✅ 𝐋\'𝐀𝐂𝐇𝐀𝐓 𝐄𝐓 𝐋𝐄 𝐏𝐑𝐄𝐓 𝐃\'𝐄𝐐𝐔𝐈𝐏𝐄𝐌𝐄𝐍𝐓𝐒 aux membres pratiquants pour apporter plus de sécurité aux pilotes lors des sorties (casque, combinaison, chaussures, gants, minerve, protège-côte, chaussures).',
      '✅ 𝐋\'𝐎𝐑𝐆𝐀𝐍𝐈𝐒𝐀𝐓𝐈𝐎𝐍 𝐃𝐄 𝐉𝐎𝐔𝐑𝐍𝐄𝐄𝐒 𝐃𝐄𝐂𝐎𝐔𝐕𝐄𝐑𝐓𝐄𝐒 𝐒𝐎𝐋𝐈𝐃𝐀𝐈𝐑𝐄𝐒 𝐃𝐄 𝐋𝐀 𝐏𝐑𝐀𝐓𝐈𝐐𝐔𝐄 𝐃𝐔 𝐊𝐀𝐑𝐓 pour les institutions et les foyers à budget limité :',
      ' ➤ ➤ ➤ Les écoles (classes primaires) à proximité du circuit choisi pour la découverte du kart, les maisons d’enfants à caractères social (MECS),… ',
      ' ➤ ➤ ➤  Les personnes ne pouvant accéder à la pratique du kart pour des raisons financières (familles nombreuses, faible revenu,…).',
      ' Ces journées ont pour but de réunir enfants et adultes en proposant le kart sous divers formats de roulage.',
    ],
  },
  {
    id: 3,
    img: 'images/membres.jpg',
    title: 'LES MEMBRES DE L\'ASSOCIATION',
    presentation: [
      '𝐋𝐄𝐒 𝐂𝐎𝐓𝐈𝐒𝐀𝐓𝐈𝐎𝐍𝐒 𝐌𝐄𝐌𝐁𝐑𝐄𝐒 :',
      'La cotisation annuelle s’élève à 40€ pour les 7-16 ans et à 60€ pour les +16 ans. Elle sera renouvelée à date anniversaire de votre adhésion.',
      '𝐋𝐄𝐒 𝐀𝐕𝐀𝐍𝐓𝐀𝐆𝐄𝐒 𝐃𝐄𝐒 𝐌𝐄𝐌𝐁𝐑𝐄𝐒 𝐏𝐑𝐀𝐓𝐈𝐐𝐔𝐀𝐍𝐓𝐒 :',
      '➤ ➤ ➤ Des sorties découvertes à tarif préférentiel sur différents circuits organisées par KCD.',
      '➤ ➤ ➤ Un prêt d’équipements sur les sorties découvertes.',
      '➤ ➤ ➤ Des réductions  sur présentation de la carte membres dans certains lieux :',
      '✅ 10% de remise au Leclerc de Sports Saint-Brévin-les-Pins',
      '✅ Tarif préférentiel au Circuit Chantemerle JOVIKART du Bignon.',
      '✅ Tarif réduit au ticket à la piste LMC Racing de Corcoué sur Logne',
      'KCD se charge d’organiser l’intégralité des sorties : recherche de circuits adaptés au projet, négociation des tarifs, logistique, encadrement par des moniteurs BPJEPS sport auto (le plus souvent possible).',
      '𝐋𝐀 𝐌𝐎𝐁𝐈𝐋𝐈𝐒𝐀𝐓𝐈𝐎𝐍 𝐃𝐄𝐒 𝐌𝐄𝐌𝐁𝐑𝐄𝐒 𝐏𝐑𝐀𝐓𝐈𝐐𝐔𝐀𝐍𝐓𝐒 𝐄𝐒𝐓 𝐒𝐎𝐔𝐇𝐀𝐈𝐓𝐄𝐄 :',
      '➤ Lors des actions/animations KCD pour récolter des fonds',
      '➤ Lors des Journées Découvertes Solidaires pour écoles, institutions de l’enfance, ou familles à budget réduit.',
      '𝐋𝐀 𝐌𝐎𝐓𝐈𝐕𝐀𝐓𝐈𝐎𝐍 𝐃𝐄 𝐂𝐇𝐀𝐂𝐔𝐍 𝐄𝐒𝐓 𝐋𝐀 𝐁𝐈𝐄𝐍𝐕𝐄𝐍𝐔𝐄  dans ces moments car il sera nécessaire d’avoir l’aide du plus grand nombre de membres pratiquants et de bénévoles pour que ces journées découvertes soient une réussite et un bon souvenir pour chacun des participants.',
      'N’hésitez pas à 𝐅𝐀𝐈𝐑𝐄 𝐂𝐎𝐍𝐍𝐀𝐈𝐓𝐑𝐄 𝐊𝐂𝐃  autour de vous pour contribuer au développement de l’association !',
    ],
  },
  {
    id: 4,
    img: 'images/reglement.jpg',
    title: 'LE RÈGLEMENT INTÉRIEUR DE L’ASSOCIATION K.C.D',
    presentation: [
      'Cette association doit respecter dans son fonctionnement, et dans son développement les statuts établis et déclarés en préfecture, (loi du 1 juillet 1901).',
      'Toute personne étant membre de cette association doit également respecter les règles et le  fonctionnement de celle-ci.',
      'K.C.D à pour objectif de récolter des fonds par divers actions, pour son fonctionnement.',
      '𝐒𝐄𝐒 𝐎𝐁𝐉𝐄𝐂𝐓𝐈𝐅𝐒 :  ',
      '➤ Achat d’équipement pilote  (casques, combinaisons, gants, minerves, chaussures). L’équipement reste la propriété de l’association.',
      '➤ De proposer  la découverte de la pratique du kart (course loisir ou roulage type location) sur différents circuits, avec une aide financière de KCD',
      '➤ De proposer l’accès à des stages de pilotage kart  avec une aide financière de KCD',
      '➤ De proposer  la découverte du kart pour des personne au budget limité, soit (par des stages ou du roulage type location).',
      '𝐒𝐎𝐍 𝐅𝐎𝐍𝐂𝐓𝐈𝐎𝐍𝐍𝐄𝐌𝐄𝐍𝐓 :',
      '➤ Les membres du bureau peuvent  s’acquitter d’une cotisation annuelle d’un montant (X) déterminé par l’assemblée générale.',
      '➤ Les adhérents pratiquants  doivent s’acquitter d’une cotisation annuelle d’un montant (x) déterminé par l’assemblée générale.',
      '➤ Les donateurs et bienfaiteurs versent une somme annuelle d’un montant libre. (un montant minimum (x) déterminé  par le bureau).',
      '➤ Les personnes bénévoles non pas l’obligation d’honorer une cotisation.',
      '𝐋𝐄𝐒 𝐌𝐄𝐌𝐁𝐑𝐄𝐒 𝐃𝐔 𝐁𝐔𝐑𝐄𝐀𝐔 𝐒𝐎𝐍𝐓 : Des personnes qui constituent le bureau de l’association (président, secrétaire, trésorier etc...) Ils peuvent être membres du bureau et adhérents, donateurs ou bienfaiteurs mais aussi  bénévoles. Ne sont admis que les adultes (18 ans et plus).',
      '𝐋𝐄𝐒 𝐀𝐃𝐇𝐄𝐑𝐄𝐍𝐓𝐒 𝐒𝐎𝐍𝐓 : Des personnes qui pratiquent l’activité kart en loisir régulièrement, ou occasionnellement, et désirent bénéficier du service de l’association. Ils peuvent être membres du bureau, bienfaiteurs, donateurs et bénévoles.Sont admis les adultes, les enfants (7 ans à 17 ans) avec l’autorisation des parents',
      '𝐋𝐄𝐒 𝐃𝐎𝐍𝐀𝐓𝐄𝐔𝐑𝐒 𝐄𝐓 𝐁𝐈𝐄𝐍𝐅𝐀𝐈𝐓𝐄𝐔𝐑𝐒 𝐒𝐎𝐍𝐓 : Des personnes ou entreprises désirant aider l’association, financièrement, ou matériellement. Ils peuvent être membres du bureau, adhérents mais aussi  bénévoles. Ne sont admis que les adultes (18 ans et plus).',
      '𝐋𝐄𝐒 𝐁𝐄𝐍𝐄𝐕𝐎𝐋𝐄𝐒 𝐒𝐎𝐍𝐓 : Des personnes qui désirent donner un peu de leur temps pour le fonctionnement de l’association (événement, déplacement, recherche de fonds etc...).Ils peuvent également être membres du bureau, adhérents, bienfaiteurs ou donateurs.  Sont admis les adultes et les jeunes de 16 ans et plus.',
      '𝐋𝐄 𝐏𝐑𝐄𝐓 𝐃\'𝐄𝐐𝐔𝐈𝐏𝐄𝐌𝐄𝐍𝐓 𝐏𝐈𝐋𝐎𝐓𝐄 : Les équipements (gants ; casque ; combinaison ; chaussures ; minerve ; protège côtes) propriété de KCD sont destinés aux adhérents pratiquants ayant réglé la cotisation annuelle. Le prêt peut être d’une durée courte (une journée ou moins), mais aussi d’une durée longue (une journée et plus). Le prêt d’équipement doit être accompagné de chèque de caution du montant du neuf. (Un chèque pour le prêt d’un casque, un chèque pour le prêt de combinaison, chaussures, gants, minerve, et protège côtes). Le chèque de caution a pour objectif la restitution de l’équipement en temps et en heure, en bon état, et propre. En cas de perte de vol, ou dégradation, le ou les chèques seront encaissés.',
      '➤ Pendant la durée du prêt, le pratiquant a la responsabilité de l’équipement. Le ou les chèques sont gardés par KCD pendant un an, à partir de la date indiquée sur celui-ci.',
      '➤ KCD  peut louer l’équipement aux personnes extérieures à l’association (montant déterminé par le bureau) qui  désirent  s’équiper pour du roulage occasionnel (type location ou course) toujours avec caution. Elle permet de faire rentrer des fonds.',
      '𝐃𝐄𝐏𝐋𝐀𝐂𝐄𝐌𝐄𝐍𝐓 𝐄𝐓 𝐓𝐑𝐀𝐍𝐒𝐏𝐎𝐑𝐓 : Pour toute sortie de roulage organisée par KCD le certificat médical peut être demandé aux pratiquants. Pour les mineurs la présence d’adultes doit être obligatoire (parents, tuteurs, ou autres responsables).',
      '➤ Les déplacements : Les sorties organisées par KCD qui exigent des déplacements avec un ou plusieurs  véhicules, sont soumises à plusieurs critères :',
      '❶ Le ou les conducteurs doivent avoir le permis de conduire.',
      '❷ Un permis de conduire de trois ans ou plus. (photocopie demandée).',
      '❸ Le véhicule doit être conforme au contrôle technique. (photocopie demandée).',
      '❹ Le véhicule doit être assuré. (photocopie demandée).',
      '❺ Le transport des mineurs doit être sous la responsabilité des parents ou tuteurs. (véhicule personnel). Dans le cas contraire, une autorisation des parents ou tuteurs sera demandée.',
      '➤ 𝐋𝐄𝐒 𝐀𝐂𝐓𝐈𝐎𝐍𝐒 𝐊𝐂𝐃 : Les représentants du bureau, les adhérents pratiquants, et autres bienfaiteurs, pourront et devront sur demande, participer à la mise en place d’actions diverses pour récolter des fonds, pour le bon fonctionnement de KCD. Les mineurs adhérents pratiquants ne sont pas soumis à cette demande. (Sauf sur proposition des parents ou tuteurs).',
      '📢 📢 𝐑𝐄𝐆𝐋𝐄𝐒 𝐏𝐑𝐄𝐌𝐈𝐄𝐑𝐄𝐒 : Toutes journées, actions, activités, mises en place par KCD doivent restées dans un esprit d’aide, sportivité et de respect de toutes règles mise en place par KCD ou existantes sur site. Dans le cas contraire des sanctions ou exclusions pourraient être prises, sans aucun remboursement des cotisations. 📢 📢',
    ],
  },
  {
    id: 5,
    img: 'images/financement.jpg',
    title: 'LES FINANCEMENTS DE L\'ASSOCIATION',
    presentation: [
      'Pour réussir à mettre en place ses différents projets, KCD prévoit de récolter des fonds sous plusieurs formes :',
      '➤ Cotisations annuelles des membres adhérents pratiquants',
      '➤ Dons personnels (soumis à la défiscalisation à hauteur de 66%, limité à 20% du revenu imposable).',
      '➤ Mise en place d’actions/animations pour récolter des fonds',
      '➤ Ressources publiques (subventions)',
      '➤ Parrainage et mécénat d’entreprises',
      ' 👍 Les 𝐂𝐎𝐓𝐈𝐒𝐀𝐓𝐈𝐎𝐍𝐒 𝐃𝐄𝐒 𝐌𝐄𝐌𝐁𝐑𝐄𝐒 et les 𝐃𝐎𝐍𝐒 𝐏𝐄𝐑𝐒𝐎𝐍𝐍𝐄𝐋𝐒 financeront principalement les sorties découvertes pour les membres pratiquants et seront répartis selon le graphique ci-dessous.',
      'Néanmoins, plusieurs bienfaiteurs et parrainages seront aussi nécessaires pour la mise en place de ces sorties membres.',
      'Une mobilisation du plus grand nombre est donc la bienvenue pour relayer les objectifs de l’association et pouvoir recueillir des fonds pour offrir un maximum de découvertes de circuits.',
      ' 👍 𝐋𝐄𝐒 𝐉𝐎𝐔𝐑𝐍𝐄𝐄𝐒 𝐃𝐄𝐂𝐎𝐔𝐕𝐄𝐑𝐓𝐄𝐒 doivent être principalement financées par les  parrainages, les mécénats et les actions mise en place par KCD au court de l’année.',
      'KCD se charge d’organiser l’intégralité de ces journées, avec l’aide du plus grand nombre de membres pratiquants, de bénévoles et de bienfaiteurs de l’association.',
    ],
    schema: 'https://www.kart-club-decouverte.fr/wp-content/uploads/2019/05/image-1.png',
  },
];
