export default [
  // {
  //   id: 7,
  //   imgCard: 'images/laser-karting-nantes.jpg',
  //   circuit: 'Circuit Laser Karting de Nantes',
  //   title: 'Une piste de 400m avec tunnel !',
  //   adress: 'Adresse : avenue du Marché Commun 44300 Nantes',
  //   date: 'RDV à 9h30 le Dimanche 12 Décembre 2021',
  // },
  {
    id: 6,
    imgCard: 'karting-st-herblain.jpg',
    circuit: 'Circuit Karting électrique de Nantes',
    title: 'Pont de 60 m avec descente en virage !',
    adress: 'Adresse : 24 rue Bobby Sand 44800 St Herblain',
    date: 'RDV à 9h30 le Dimanche 14 Novembre 2021',
    description: [
      ' Piste PRIVATISEE pour KCD',
      ' Fin de la sortie vers 12h30',
      ' Accueil autour d’un café et autres boissons.',
    ],
    classAdult: '13',
    materialAdult: 'kart électrique',
    tarifAdultMember: '40',
    tarifAdultExt: '48',
    tarifAdult: '50',
    sessionAdult: [
      'Accueil & briefing',
      'Essais chrono : 8 min',
      'Course : 18 tours',
      'Finale : 18 tours',
      'Podium',
    ],
    classYoung: '',
    materialYoung: '',
    tarifYoungMember: '',
    tarifYoungExt: '',
    tarifYoung: '',
    sessionYoung: [''],
    classMinJunior: '7',
    classMaxJunior: '12',
    materialJunior: 'kart électrique',
    tarifJuniorMember: '28',
    tarifJuniorExt: '36',
    tarifJunior: '36',
    sessionJunior: [
      'Accueil & briefing',
      '3 sessions de 10 min',
      'Podium',
    ],
  },
  {
    id: 5,
    imgCard: 'circuit-jovikart.jpg',
    circuit: 'Circuit Jovikart',
    title: 'Première sortie nocturne !',
    adress: 'Adresse : Z.A. La Forêt – 44140 Le Bignon',
    date: 'RDV à 19h le Vendredi 22 Octobre 2021',
    description: [
      ' Piste PRIVATISEE pour KCD',
      ' Avec pizza et boissons pour tous offert par KCD.',
    ],
    classAdult: '14',
    materialAdult: '390cc 14cv',
    tarifAdultMember: '34',
    tarifAdultExt: '48',
    tarifAdult: '55',
    sessionAdult: [
      'Accueil & briefing',
      'Essais libre : 5 min',
      'Essais chrono : 10 min',
      'Finale : 15 min',
      'Podium',
    ],
    classYoung: '11',
    materialYoung: '270cc 9cv',
    tarifYoungMember: '28',
    tarifYoungExt: '40',
    tarifYoung: '48',
    sessionYoung: [
      'Accueil & briefing',
      'Essais libres : 5 min',
      'Essais chrono : 10 min',
      'Finale : 15 min',
      'Podium',
    ],
    classMinJunior: '7',
    classMaxJunior: '10',
    materialJunior: '160cc 4,5cv',
    tarifJuniorMember: '10',
    tarifJuniorExt: '12',
    tarifJunior: '',
    sessionJunior: [
      '3 sessions de 10 min',
    ],
  },
  {
    id: 4,
    imgCard: 'circuit-plesse.jpg',
    circuit: 'Circuit Solokart',
    title: 'Le plus grand circuit d\'Europe !',
    adress: 'Adresse : Lieu-dit « La Piardière », 44630 Plessé',
    date: 'RDV à 9h30 le Dimanche 4 Juillet 2021',
    description: [
      'Une 11ème sortie sur la plus grande piste d’Europe. Un circuit de 1350m, un deuxième de 800m.',
      'Matériel tout neuf pour les Juniors en 270cc !',
      'Et un héliport pour ceux qui préfèrent arriver en hélicoptère !',
      'Sensations et vitesse assurées.',
    ],
    classAdult: '15',
    materialAdult: '390cc 14cv',
    tarifAdultMember: '55',
    tarifAdultExt: '65',
    tarifAdult: '',
    sessionAdult: [
      'Accueil & briefing',
      'Essais libres : 10 min',
      'Course : 10 min',
      'Finale : 10 min',
      'Podium',
    ],
    classYoung: '12',
    materialYoung: '270cc 9cv',
    tarifYoungMember: '40',
    tarifYoungExt: '47',
    tarifYoung: '',
    sessionYoung: [
      'Accueil & briefing',
      'Essais libres : 10 min',
      'Course : 10 min',
      'Finale : 10 min',
      'Podium',
    ],
    classMinJunior: '7',
    classMaxJunior: '10',
    materialJunior: '160cc 4,5cv',
    tarifJuniorMember: 10,
    tarifJuniorExt: 10,
    tarifJunior: 17,
    sessionJunior: [
      'Accueil & briefing',
      '3 sessions de 10 min',
    ],
  },
  {
    id: 3,
    imgCard: 'circuit-lmc.jpg',
    circuit: 'Circuit LMC',
    title: 'Le circuit le plus rapide de la région nantaise !',
    adress: 'Adresse : Lieu-dit « Grissauland » 44650 Corcoué sur logne',
    date: 'RDV à 9h30 le Dimanche 30 mai 2021',
    description: [
      'Une 10ème sortie sur la piste la plus rapide depuis le début des sorties proposées par l’asssociation.',
      'Un circuit de 800m de long par 8m de large, alliant vitesse et possibilités de dépassements.',
      'Moins de technique mais des sensations assurées !',
    ],
    classAdult: '15',
    materialAdult: '390cc 14cv',
    tarifAdultMember: '39',
    tarifAdultExt: '49',
    tarifAdult: '',
    sessionAdult: [
      'Accueil & briefing',
      'Essais libres : 10 min',
      'Course : 5 min',
      'Finale : 15 min',
      'Podium',
    ],
    classYoung: '12',
    materialYoung: '270cc 9cv',
    tarifYoungMember: '29',
    tarifYoungExt: '39',
    tarifYoung: '',
    sessionYoung: [
      'Accueil & briefing',
      'Essais libres : 10 min',
      'Course : 10 min',
      'Finale : 10 min',
      'Podium',
    ],
    classMinJunior: '',
    classMaxJunior: '',
    materialJunior: '',
    tarifJuniorMember: '',
    tarifJuniorExt: '',
    tarifJunior: '',
    sessionJunior: [
      '',
    ],
  },
  {
    id: 2,
    imgCard: 'circuit-mrk.jpg',
    circuit: 'Circuit Martini Racing Kart',
    title: 'Circuit qui allie vitesse et technicité !',
    adress: 'Adresse : Route de Cholet - ZI des judices, 85300 Challans',
    date: 'RDV à 10h00 le Dimanche 5 Juillet 2020',
    description: [
      ' Piste PRIVATISEE pour KCD',
      ' Avec une consommation sans alcool offerte pour les pilotes.',
    ],
    classAdult: '15',
    materialAdult: '270cc 9cv',
    tarifAdultMember: '37',
    tarifAdultExt: '44',
    tarifAdult: '48',
    sessionAdult: [
      'Accueil & briefing',
      'Essais chrono : 8 min',
      'Course : 10 min',
      'Finale : 12 min',
      'Podium',
    ],
    classYoung: '',
    materialYoung: '',
    tarifYoungMember: '',
    tarifYoungExt: '',
    tarifYoung: '',
    sessionYoung: [
      '',
    ],
    classMinJunior: '7',
    classMaxJunior: '14',
    materialJunior: '120cc 4.5cv',
    tarifJuniorMember: '27',
    tarifJuniorExt: '32',
    tarifJunior: '39',
    sessionJunior: [
      'Accueil & briefing',
      'Essais chrono : 10 min',
      'Course : 10 min',
      'Finale : 10 min',
      'Podium',
    ],
  },
];
