export default [
  {
    id: 1,
    imgCard: 'images/circuit-jovikart.jpg',
    circuit: 'Circuit Jovikart',
    title: 'Première sortie nocturne !',
    adress: 'Adresse : Z.A. La Forêt – 44140 Le Bignon',
    date: 'RDV à 19h le Vendredi 22 Octobre 2021',
  },
  {
    id: 2,
    imgCard: 'images/circuit-plesse.jpg',
    circuit: 'Circuit Solokart',
    title: 'Le plus grand circuit d\'Europe !',
    adress: 'Adresse : Lieu-dit « La Piardière », 44630 Plessé',
    date: 'RDV à 9h30 le Dimanche 4 Juillet 2021',
  },
  {
    id: 3,
    imgCard: 'images/circuit-lmc.jpg',
    circuit: 'Circuit LMC',
    title: 'Le circuit le plus rapide de la région nantaise !',
    adress: 'Adresse : Lieu-dit « Grissauland » 44650 Corcoué sur logne',
    date: 'RDV à 9h30 le Dimanche 30 mai 2021',
  },
  {
    id: 4,
    imgCard: 'images/circuit-mrk.jpg',
    circuit: 'Circuit Martini Racing Kart',
    title: 'Circuit qui allie vitesse et technicité !',
    adress: 'Adresse : Route de Cholet - ZI des judices, 85300 CHALLANS',
    date: 'RDV à 10h00 le Dimanche 5 Juillet 2020',
  },
  {
    id: 5,
    imgCard: 'images/circuit-jade.jpg',
    circuit: 'Circuit Racing Karting Jade',
    title: '2 circuits reliés pour 1040M de développé !',
    adress: 'Adresse : 14 Rue des Forgerons, 44730 Saint-Michel-Chef-Chef',
    date: 'RDV à 10h00 le Dimanche 7 Juin 2020',
  },
];
